on:
  repository_dispatch:
  push:
    branches: [master]

name: Render and Publish

# you need these permissions to publish to GitHub pages
permissions:
  contents: write
  pages: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    # run only on upstream, not on downstream
    if: github.repository == 'dossgollin-lab/dossgollin-lab.github.io'

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: true

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Update bibliography
        run: |
          cd _bibliography
          git branch -u origin/master master
          cd ..
          git submodule update --remote --recursive

      - name: Set up Conda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: dossgollin-lab
          environment-file: _environment.yml
          python-version: 3.12

      - name: Conda info
        shell: bash -el {0}
        run: conda info

      - name: Generate Publication Files
        run: |
          conda activate dossgollin-lab
          python bibtex_to_qmd.py

      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
